# Site
title:              Atiqur Safayat
bio:                'Atiqur Rahman Atiq'
description:        "Created by atiq"
reading_time:       true
words_per_minute:   200
logo:               'mbeshrlog.png'
locale:             ar_YE
url:                https://fb.com/safayat.atiqur

# Jekyll
permalink:          /:title/
markdown:           kramdown      
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            false


# Comments
disqus_shortname:  

# Social
# if you don't have any of social below, comment the line.
google:		          
  #analytics:	UA-80564042-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:			atiqursafayat@gmail.com
#twitter:            
facebook:           safayat.atiqur
github:             atiqursafayat
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:          mulham94
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
# Gems
excerpt_separator: <!--more-->
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-archives

paginate: 12
paginate_path: /page:num/

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
